production:
  domain: "ogc@larry.ogtastic.com"
  deploy_to: "/opt/ogc/var/www/larry-production.ogtastic.com"
  deploy_config_to: "/opt/ogc/var/www/project_config"
  repository: "git://github.com/rick/larry.git"
  config_repository: "git@git.ogtastic.com:project_config.git"
  rake_env:
    RAILS_ENV: 'production'
staging:
  domain: "ogc@larry.ogtastic.com"
  deploy_to: "/opt/ogc/var/www/larry-staging.ogtastic.com"
  deploy_config_to: "/opt/ogc/var/www/project_config"
  repository: "git://github.com/rick/larry.git"
  config_repository: "git@git.ogtastic.com:project_config.git"
  rake_env:
    RAILS_ENV: 'production'

